# Generated by Django 4.2.23 on 2025-07-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='9999999999', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('wash_and_fold', 'Wash & Fold'), ('dry_cleaning', 'Dry Cleaning'), ('ironing', 'Ironing')], default='wash_and_fold', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total_clothes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
