# Generated by Django 4.2.23 on 2025-07-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='service',
        ),
    ]
