# Generated by Django 4.2.23 on 2025-07-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('notice', models.CharField(max_length=50)),
                ('bangalore', models.CharField(max_length=10)),
                ('experience', models.CharField(max_length=20)),
                ('currentRole', models.CharField(max_length=100)),
                ('currentPay', models.CharField(max_length=100)),
                ('desiredPay', models.CharField(max_length=100)),
                ('commute', models.CharField(max_length=20)),
                ('nightShift', models.CharField(max_length=10)),
                ('referral', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
