# Generated by Django 4.2.23 on 2025-07-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='currentPay',
            new_name='coverLetter',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='currentRole',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='bangalore',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='commute',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='desiredPay',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='nightShift',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='referral',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(default='Customer Service Representative', max_length=100),
        ),
    ]
