# Generated by Django 4.2.23 on 2025-07-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_job_rename_currentpay_jobapplication_coverletter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='coverLetter',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
