# Generated by Django 4.2.23 on 2025-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_truecaller_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='truecaller_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
