# Generated by Django 4.2.23 on 2025-07-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='icon',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contentsection',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
